packages:
  - apps/*
  - packages/*
  - examples/*
allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - hono@4.13.0
  - fumadocs-core@16.14.3
  - fumadocs-mdx@15.2.3
peerDependencyRules:
  allowedVersions:
    "@solana-program/token-2022>@solana/sysvars": ">=5 <7"
overrides:
  hono: 4.13.0
  nanoid@<3.3.18: 3.3.18
  postcss: 8.5.25
  sharp: 0.35.3
